import { createServer, type Server } from "node:net";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { Keypair, StrKey } from "@stellar/stellar-sdk";
import { setupSshAgentForWallet } from "../../src/ssh-agent-setup.js";
import { makeFakeSshAgentFixture } from "../helpers/fake-ssh-agent.js";
import { makeTempDir } from "../helpers/temp-dir.js";

// ---------------------------------------------------------------------------
// Helper: a minimal SSH agent server that always returns zero identities
// ---------------------------------------------------------------------------
const SSH2_AGENT_IDENTITIES_ANSWER = 12;

function writeUint32(value: number): Buffer {
  const buf = Buffer.alloc(4);
  buf.writeUInt32BE(value, 0);
  return buf;
}

function buildEmptyIdentitiesResponse(): Buffer {
  const body = Buffer.concat([
    Buffer.from([SSH2_AGENT_IDENTITIES_ANSWER]),
    writeUint32(0), // zero keys
  ]);
  return Buffer.concat([writeUint32(body.length), body]);
}

async function makeEmptyAgentServer(): Promise<{
  server: Server;
  socketPath: string;
  cleanup: () => Promise<void>;
}> {
  const rootDir = makeTempDir("walleterm-empty-ssh-agent-");
  const socketPath = join(rootDir, "agent.sock");

  const server = createServer((socket) => {
    let buffer = Buffer.alloc(0);
    socket.on("data", (chunk: Buffer) => {
      buffer = Buffer.concat([buffer, chunk]);
      while (buffer.length >= 4) {
        const msgLen = buffer.readUInt32BE(0);
        const totalLen = 4 + msgLen;
        if (buffer.length < totalLen) break;
        buffer = buffer.subarray(totalLen);
        // Always respond with empty identities regardless of the request type
        socket.write(buildEmptyIdentitiesResponse());
      }
    });
  });

  await new Promise<void>((resolve) => {
    server.listen(socketPath, () => resolve());
  });

  return {
    server,
    socketPath,
    cleanup: () => new Promise((resolve) => server.close(() => resolve())),
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
describe("ssh-agent-setup unit", () => {
  // Track fixtures for cleanup
  const cleanups: (() => Promise<void>)[] = [];

  afterEach(async () => {
    for (const fn of cleanups) {
      await fn();
    }
    cleanups.length = 0;
  });

  // -----------------------------------------------------------------------
  // Single-key success case
  // -----------------------------------------------------------------------
  it("returns correct backend, socket_path, key info, and config_snippet for a single key", async () => {
    const fx = await makeFakeSshAgentFixture();
    cleanups.push(fx.cleanup);

    const result = await setupSshAgentForWallet({
      backend: "custom",
      socketPath: fx.socketPath,
    });

    // backend and socket_path reflect the input
    expect(result.backend).toBe("custom");
    expect(result.socket_path).toBe(fx.socketPath);

    // exactly one key returned
    expect(result.keys).toHaveLength(1);

    const key = result.keys[0]!;
    // stellar_address is a valid G... address matching the fixture keypair
    expect(key.stellar_address).toBe(fx.stellarAddress);
    expect(StrKey.isValidEd25519PublicKey(key.stellar_address)).toBe(true);

    // public_key_hex matches the fixture
    expect(key.public_key_hex).toBe(fx.publicKeyHex);
    expect(key.public_key_hex).toHaveLength(64); // 32 bytes hex-encoded

    // comment is the one generated by the fake agent
    expect(key.comment).toBe(`fake-key-${fx.stellarAddress.slice(0, 8)}`);

    // ref follows the ssh-agent:// URI scheme with a socket query param
    expect(key.ref).toBe(
      `ssh-agent://custom/${fx.stellarAddress}?socket=${encodeURIComponent(fx.socketPath)}`,
    );

    // config_snippet is valid TOML for a single delegated signer
    expect(result.config_snippet).toContain("[[smart_accounts.<alias>.delegated_signers]]");
    expect(result.config_snippet).toContain('name = "ssh-agent-0"');
    expect(result.config_snippet).toContain(`address = "${fx.stellarAddress}"`);
    expect(result.config_snippet).toContain(`secret_ref = "${key.ref}"`);
    expect(result.config_snippet).toContain("enabled = true");
  });

  // -----------------------------------------------------------------------
  // Multiple-key success case
  // -----------------------------------------------------------------------
  it("handles multiple keys with correct indices in config snippet", async () => {
    // We need a custom server that returns two keys
    const kp1 = Keypair.random();
    const kp2 = Keypair.random();

    const rootDir = makeTempDir("walleterm-multi-ssh-agent-");
    const socketPath = join(rootDir, "agent.sock");

    function buildKeyBlob(pubkey: Buffer): Buffer {
      const writeStr = (data: Buffer | string): Buffer => {
        const bytes = typeof data === "string" ? Buffer.from(data) : data;
        return Buffer.concat([writeUint32(bytes.length), bytes]);
      };
      return Buffer.concat([writeStr("ssh-ed25519"), writeStr(pubkey)]);
    }

    function buildMultiIdentitiesResponse(keypairs: Keypair[]): Buffer {
      const parts: Buffer[] = [
        Buffer.from([SSH2_AGENT_IDENTITIES_ANSWER]),
        writeUint32(keypairs.length),
      ];
      for (const kp of keypairs) {
        const keyBlob = buildKeyBlob(Buffer.from(kp.rawPublicKey()));
        const comment = `fake-key-${kp.publicKey().slice(0, 8)}`;
        const writeStr = (data: Buffer | string): Buffer => {
          const bytes = typeof data === "string" ? Buffer.from(data) : data;
          return Buffer.concat([writeUint32(bytes.length), bytes]);
        };
        parts.push(writeStr(keyBlob), writeStr(comment));
      }
      const body = Buffer.concat(parts);
      return Buffer.concat([writeUint32(body.length), body]);
    }

    const server = createServer((socket) => {
      let buffer = Buffer.alloc(0);
      socket.on("data", (chunk: Buffer) => {
        buffer = Buffer.concat([buffer, chunk]);
        while (buffer.length >= 4) {
          const msgLen = buffer.readUInt32BE(0);
          const totalLen = 4 + msgLen;
          if (buffer.length < totalLen) break;
          buffer = buffer.subarray(totalLen);
          socket.write(buildMultiIdentitiesResponse([kp1, kp2]));
        }
      });
    });

    await new Promise<void>((resolve) => {
      server.listen(socketPath, () => resolve());
    });

    cleanups.push(() => new Promise((resolve) => server.close(() => resolve())));

    const result = await setupSshAgentForWallet({
      backend: "custom",
      socketPath,
    });

    // Two keys returned
    expect(result.keys).toHaveLength(2);

    // Verify each key matches its keypair
    const addr1 = kp1.publicKey();
    const addr2 = kp2.publicKey();
    expect(result.keys[0]!.stellar_address).toBe(addr1);
    expect(result.keys[1]!.stellar_address).toBe(addr2);

    expect(result.keys[0]!.public_key_hex).toBe(
      Buffer.from(kp1.rawPublicKey()).toString("hex"),
    );
    expect(result.keys[1]!.public_key_hex).toBe(
      Buffer.from(kp2.rawPublicKey()).toString("hex"),
    );

    expect(result.keys[0]!.comment).toBe(`fake-key-${addr1.slice(0, 8)}`);
    expect(result.keys[1]!.comment).toBe(`fake-key-${addr2.slice(0, 8)}`);

    // Both refs should include the socket param
    expect(result.keys[0]!.ref).toContain(`ssh-agent://custom/${addr1}`);
    expect(result.keys[1]!.ref).toContain(`ssh-agent://custom/${addr2}`);

    // config_snippet: first entry has no leading newline, second does
    const snippet = result.config_snippet;
    expect(snippet).toContain('name = "ssh-agent-0"');
    expect(snippet).toContain('name = "ssh-agent-1"');
    expect(snippet).toContain(`address = "${addr1}"`);
    expect(snippet).toContain(`address = "${addr2}"`);

    // The snippet should have exactly two [[smart_accounts...]] blocks
    const blockCount = (snippet.match(/\[\[smart_accounts\.<alias>\.delegated_signers\]\]/g) || [])
      .length;
    expect(blockCount).toBe(2);

    // First block starts at position 0 (no leading newline), second is separated
    expect(snippet.startsWith("[[smart_accounts.<alias>.delegated_signers]]")).toBe(true);
  });

  // -----------------------------------------------------------------------
  // Backend and socket_path passthrough (no explicit socketPath -> resolveSocketPath default)
  // -----------------------------------------------------------------------
  it("returns the backend value passed in opts", async () => {
    const fx = await makeFakeSshAgentFixture();
    cleanups.push(fx.cleanup);

    const result = await setupSshAgentForWallet({
      backend: "1password",
      socketPath: fx.socketPath,
    });

    expect(result.backend).toBe("1password");
    expect(result.socket_path).toBe(fx.socketPath);
  });

  // -----------------------------------------------------------------------
  // Ref without socketPath (custom backend requires socket, so use system)
  // -----------------------------------------------------------------------
  it("builds ref without socket query param when socketPath is not provided", async () => {
    const fx = await makeFakeSshAgentFixture();
    cleanups.push(fx.cleanup);

    // Temporarily set SSH_AUTH_SOCK to point at the fake agent
    const prev = process.env.SSH_AUTH_SOCK;
    process.env.SSH_AUTH_SOCK = fx.socketPath;
    try {
      const result = await setupSshAgentForWallet({
        backend: "system",
      });

      expect(result.socket_path).toBe(fx.socketPath);
      // ref should NOT have a ?socket= query because socketPath was undefined
      const key = result.keys[0]!;
      expect(key.ref).toBe(`ssh-agent://system/${fx.stellarAddress}`);
      expect(key.ref).not.toContain("?socket=");
    } finally {
      if (prev === undefined) delete process.env.SSH_AUTH_SOCK;
      else process.env.SSH_AUTH_SOCK = prev;
    }
  });

  // -----------------------------------------------------------------------
  // Error: no Ed25519 keys found
  // -----------------------------------------------------------------------
  it("throws when no Ed25519 keys are found in the agent", async () => {
    const empty = await makeEmptyAgentServer();
    cleanups.push(empty.cleanup);

    await expect(
      setupSshAgentForWallet({
        backend: "custom",
        socketPath: empty.socketPath,
      }),
    ).rejects.toThrow(`No Ed25519 keys found in SSH agent at ${empty.socketPath}`);
  });

  // -----------------------------------------------------------------------
  // Config snippet TOML structure validation
  // -----------------------------------------------------------------------
  it("config_snippet lines follow exact TOML format per key", async () => {
    const fx = await makeFakeSshAgentFixture();
    cleanups.push(fx.cleanup);

    const result = await setupSshAgentForWallet({
      backend: "custom",
      socketPath: fx.socketPath,
    });

    const lines = result.config_snippet.split("\n");
    expect(lines[0]).toBe("[[smart_accounts.<alias>.delegated_signers]]");
    expect(lines[1]).toBe('name = "ssh-agent-0"');
    expect(lines[2]).toBe(`address = "${fx.stellarAddress}"`);
    expect(lines[3]).toBe(`secret_ref = "${result.keys[0]!.ref}"`);
    expect(lines[4]).toBe("enabled = true");
    expect(lines).toHaveLength(5);
  });

  // -----------------------------------------------------------------------
  // Specific keypair passthrough
  // -----------------------------------------------------------------------
  it("uses the specific keypair provided to the fixture", async () => {
    const kp = Keypair.random();
    const fx = await makeFakeSshAgentFixture(kp);
    cleanups.push(fx.cleanup);

    const result = await setupSshAgentForWallet({
      backend: "custom",
      socketPath: fx.socketPath,
    });

    expect(result.keys[0]!.stellar_address).toBe(kp.publicKey());
    expect(result.keys[0]!.public_key_hex).toBe(
      Buffer.from(kp.rawPublicKey()).toString("hex"),
    );
  });
});
